**Our group is of five and our names are as follows**
KEMIGABO CLAIRE ||	2100713786	|| 21/U/13786/EVE, 
KATAIKE ANITA REBECCA ||	2100704746 ||	21/U/04746/EVE,  
NABAGESERA HADIJAH ||	2100707648 ||	21/U/07648/EVE,  
KAYIIRA RICHARD WILSON || 	2100711717 ||	21/U/11717/PS, 
MUGAGGA BENJAMIN KASAGGA ||	2100715419 ||	21/U/15419/EVE



**Install libraries**

In [1]:
import numpy as np
import pandas as pd
import sklearn

import matplotlib.pyplot as plt

**Import dataset**

In [2]:
file_path = '/home/kmbenjie/Desktop/machine_learning/ml_asgn_ws/wine_pred_thing/winequality_red.csv'
data = pd.read_csv(file_path)
data.head(4)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides   
0            7.4              0.70         0.00             1.9      0.076  \
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates   
0                 11.0                  34.0   0.9978  3.51       0.56  \
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6

**Data Preprocessing**

In [3]:
data['quality'] = data['quality'].map({3 : 'bad', 4 :'bad', 5: 'bad',
                                      6: 'good', 7: 'good', 8: 'good'})

data['quality'].value_counts()

quality
good    855
bad     744
Name: count, dtype: int64

In [4]:
# creating dependent and independent variables

x = data.iloc[:,:11]
y = data.iloc[:,11]

# determining the shape of x and y.
print(x.shape)
print(y.shape)

(1599, 11)
(1599,)


In [5]:
# dividing the dataset in training and testing set

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 44)

# determining the shapes of training and testing sets
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1199, 11)
(1199,)
(400, 11)
(400,)


In [6]:
# standard scaling 
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

Modelling

Decision Tree

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

# creating model
model = DecisionTreeClassifier()

# feeding the training set into the model
model.fit(x_train, y_train)

# predicting the results for the test set
y_pred = model.predict(x_test)

# calculating the training and testing accuracies
print("Training accuracy :", model.score(x_train, y_train))
print("Testing accuracy :", model.score(x_test, y_test))

print("-------------------------------------------------")
# classification report
print(classification_report(y_test, y_pred))

# confusion matrix
print(confusion_matrix(y_test, y_pred))

Training accuracy : 1.0
Testing accuracy : 0.7125
-------------------------------------------------
              precision    recall  f1-score   support

         bad       0.73      0.69      0.71       204
        good       0.70      0.73      0.71       196

    accuracy                           0.71       400
   macro avg       0.71      0.71      0.71       400
weighted avg       0.71      0.71      0.71       400

[[141  63]
 [ 52 144]]


In [8]:
#evaluation for decision tree model using cross validation.

model_eval = cross_val_score(estimator = model, X = x_train, y = y_train, cv = 10)
model_eval.mean()


0.7389985994397759

Random  Forest

In [9]:


# creating the model
model = RandomForestClassifier(n_estimators = 200)

# feeding the training set into the model
model.fit(x_train, y_train)

# predicting the results for the test set
y_pred = model.predict(x_test)

# calculating the training and testing accuracies
print("Training accuracy :", model.score(x_train, y_train))
print("Testing accuracy :", model.score(x_test, y_test))

print("-------------------------------------------------")
# classification report
print(classification_report(y_test, y_pred))

# confusion matrix
print(confusion_matrix(y_test, y_pred))



Training accuracy : 1.0
Testing accuracy : 0.7825
-------------------------------------------------
              precision    recall  f1-score   support

         bad       0.81      0.75      0.78       204
        good       0.76      0.81      0.79       196

    accuracy                           0.78       400
   macro avg       0.78      0.78      0.78       400
weighted avg       0.78      0.78      0.78       400

[[154  50]
 [ 37 159]]


In [10]:
#evaluation for random forest model using cross validation.

model_eval = cross_val_score(estimator = model, X = x_train, y = y_train, cv = 10)
model_eval.mean()

0.8040616246498601

### Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression

# creating the model
model = LogisticRegression()

# feeding the training set into the model
model.fit(x_train, y_train)

# predicting the results for the test set
y_pred = model.predict(x_test)

# calculating the training and testing accuracies
print("Training accuracy :", model.score(x_train, y_train))
print("Testing accuracy :", model.score(x_test, y_test))

# classification report
print(classification_report(y_test, y_pred))

# confusion matrix
print(confusion_matrix(y_test, y_pred))

Training accuracy : 0.7472894078398665
Testing accuracy : 0.7225
              precision    recall  f1-score   support

         bad       0.75      0.69      0.72       204
        good       0.70      0.76      0.73       196

    accuracy                           0.72       400
   macro avg       0.72      0.72      0.72       400
weighted avg       0.72      0.72      0.72       400

[[141  63]
 [ 48 148]]


### Support Vector Machine

In [12]:
from sklearn.svm import SVC

# creating the model
model = SVC()

# feeding the training set into the model
model.fit(x_train, y_train)

# predicting the results for the test set
y_pred = model.predict(x_test)

# calculating the training and testing accuracies
print("Training accuracy :", model.score(x_train, y_train))
print("Testing accuracy :", model.score(x_test, y_test))

Training accuracy : 0.8098415346121768
Testing accuracy : 0.73


#### Trying to find the best parameters for the SVC model

In [ ]:
from sklearn.model_selection import GridSearchCV

param = {
    'C': [0.8,0.9,1,1.1,1.2,1.3,1.4],
    'kernel':['linear', 'rbf'],
    'gamma' :[0.1,0.8,0.9,1,1.1,1.2,1.3,1.4]
}
grid_svc = GridSearchCV(model, param_grid = param, scoring = 'accuracy', cv = 10)
